sudo: required
services:
        - docker

before_install:
        - docker build -t nkarthik77/docker-react -f Dockerfile.dev .

script:
        - docker run nkarthik77/docker-react npm run test -- --coverage
