sudo: required
services:
        - docker

before_install:
        - docker build -t nkarthik77/docker-react -f Dockerfile.dev .

script:
        - docker run nkarthik77/docker-react npm run test -- --coverage

deploy:
        provider: elasticbeanstalk
        region: "us-east-1"
        app: "docker-react"
        env: "DockerReact-env"
        bucker_name: "elasticbeanstalk-us-east-1-285704482825"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: "$AWS_SECRET_KEY"
